### ISSUE TITLE
non-midnight start hour not working as anticipated

### ISSUE THREAD

**Issue by kenirwin** [cazzerson/Suma#34]
Hi folks,

I've configured our Suma nightly reports to use the new start-hour flag, but I'm not seeing it reflected in our resulting data. I'm using:
nightlyEmail.php locations --html --hide-zeros --start-hour=0400 

The header of the email acknowledges the start-hour flag:
"NOTICE: The 24-Hour period of this report has been modified to start at 04:00."

But the data we're getting shows all the data from the calendar day-before (today it's all data from 5-11 instead of what I expected, which was 2015-05-11 04:00:00 to 2015-05-12 04:00:00. I see calendar-day-yesterday's 00:30 count at the beginning of the list instead of calendar-day-today's 00:30 count at the end of the list.

Any ideas? Am I implementing it incorrectly? 

Thanks
Ken

**Comment by bretdavidson** [comment]
Hi Ken,

Are you getting the expected output if you just run nightlyEmail.php --start-hour=0400?

**Comment by kenirwin** [comment]
Yes -- I get the same response when I only use the start-hour flag

**Comment by bretdavidson** [comment]
Right now the hours on the nightlyEmail report aren't reordered when the startHour is changed like they are on the Timeseries Report. Can you confirm that the numbers actually represent the wrong data? Or is it just the ordering? I can work on a patch to reorder the times when startHour is active, but it will likely be a few days.

Thanks!

**Comment by kenirwin** [comment]
Oh! I thought I checked for that possibility, but I was wrong. Looking at the data, I did get the right day's data, just positioned so it looks like it's the wrong days. A patch to re-order the output would be perfect.

Thanks
Ken

**Comment by bretdavidson** [comment]
Pushed a fix to the `sortHours` branch for reference as this probably won't make it into master for a couple of weeks. Going to go ahead and close this.

Thanks,

Bret
