### ISSUE TITLE
Angular error trying to generate reports

### ISSUE THREAD

**Issue by Trott** [cazzerson/Suma#36]
We've been following along at http://cazzerson.github.io/Suma/developer/ to get Suma up and running.

We have the data entry part working just fine. 

When we try to generate a report (say, by going to https://suma.example.edu/suma/analysis/reports/#/timeseries), instead of reports with what little data we have in the system, we instead get:

* A malformed page that looks like Angular is not processing templates properly or something
* No report at all, just the spinning gif process indicators
* The following error in the browser console:

I'm hoping that this is something obvious to the Suma/Angular literate. Help?

```
Error: [$injector:unpr] Unknown provider: processTimeSeriesDataProvider <- processTimeSeriesData <- data
http://errors.angularjs.org/1.3.15/$injector/unpr?p0=processTimeSeriesDataProvider%20%3C-%20processTimeSeriesData%20%3C-NaNata
    at https://suma.example.edu/suma/analysis/reports/scripts/scripts.min.js:3:20540
    at https://suma.example.edu/suma/analysis/reports/scripts/scripts.min.js:4:6585
    at Object.d [as get] (https://suma.example.edu/suma/analysis/reports/scripts/scripts.min.js:4:5755)
    at https://suma.example.edu/suma/analysis/reports/scripts/scripts.min.js:4:6682
    at d (https://suma.example.edu/suma/analysis/reports/scripts/scripts.min.js:4:5755)
    at Object.e [as invoke] (https://suma.example.edu/suma/analysis/reports/scripts/scripts.min.js:4:6092)
    at Object.$get (https://suma.example.edu/suma/analysis/reports/scripts/scripts.min.js:4:4562)
    at Object.e [as invoke] (https://suma.example.edu/suma/analysis/reports/scripts/scripts.min.js:4:6125)
    at https://suma.example.edu/suma/analysis/reports/scripts/scripts.min.js:4:6702
    at d (https://suma.example.edu/suma/analysis/reports/scripts/scripts.min.js:4:5755)
```

![screen shot 2015-11-18 at 3 26 56 pm](https://cloud.githubusercontent.com/assets/718899/11257784/e85da488-8e08-11e5-871d-b34be8d71863.png)

![screen shot 2015-11-18 at 3 27 05 pm](https://cloud.githubusercontent.com/assets/718899/11257788/ec038bde-8e08-11e5-9f94-cec919cf3294.png)

![screen shot 2015-11-18 at 3 27 15 pm](https://cloud.githubusercontent.com/assets/718899/11257789/ee53aaae-8e08-11e5-9be4-2273d74894f5.png)

/cc @ellestad

**Comment by bretdavidson** [comment]
Hi Rich,

Thanks for taking a look at Suma and reaching out with your question. Could you clarify if you are trying to install Suma for a production instance or are hoping to do some custom report development? If the former, you shouldn't need to reference the developer docs at all and should instead use http://cazzerson.github.io/Suma/installation/. If the latter, this might be an issue with Apache aliases, referenced here: http://cazzerson.github.io/Suma/developer/#apache-configuration-note. Another option for doing development work is to use our [Suma-Vagrant](https://github.com/NCSU-Libraries/Suma-Vagrant) environment which might be helpful as a reference for configuration as well.

Best,

Bret

**Comment by Trott** [comment]
We're just trying to do a vanilla install with default reports etc. I reverted the changes to `analysis/reports/scripts` that were the result of my `grunt` run and now it seems to be working. Thanks for pointing out that I was following the wrong instructions!

**Comment by Trott** [comment]
Er, uh, well, I spoke too soon. It's not working (yet) but *this* problem with Angular is gone. I'll keep debugging/troubleshooting. If I hit another wall, I should open a separate issue here?

**Comment by Trott** [comment]
OK, other issue was that we needed to set `date.timezone` in php.ini. All is good now. Thanks again.

**Comment by bretdavidson** [comment]
Great! Glad everything is working. Let us know how it works out.

Best,

Bret
