### ISSUE TITLE
Error when trying to load initiative

### ISSUE THREAD

**Issue by dereknorton** [cazzerson/Suma#37]
I am getting an error when trying to load an initiative via the client.
The initiative is enabled 

Uncaught TypeError: Cannot read property 'length' of nulln.extend.each @ jquery.min.js:2
parseLocs @ spaceassess.js:307
(anonymous function) @ spaceassess.js:276j @ jquery.min.js:2
k.add @ jquery.min.js:2
(anonymous function) @ spaceassess.js:270
(anonymous function) @ persistence.store.sql.js:729
(anonymous function) @ persistence.store.websql.js:86

**Comment by cazzerson** [comment]
Hi Derek,

Could you check to see if the location tree associated with that initiative has any locations?

**Comment by dereknorton** [comment]
It did not, and now it works! Thanks so much!
