### ISSUE TITLE
Can't get analytics out of v2.14.0, error messages unhelpful

### ISSUE THREAD

**Issue by jsnshrmn** [cazzerson/Suma#38]
When I run the nightly script
```
$ sudo php /srv/suma/htdocs/analysis/reports/lib/php/nightly.php
 Error: exception 'Exception' with message 'Internal Server Error. ' in /srv/suma/app/analysis/reports/lib/php/ServerIO.php:197
Stack trace:
#0 /srv/suma/app/analysis/reports/lib/php/ServerIO.php(122): ServerIO->sendRequest('counts/id/1/for...')
#1 /srv/suma/app/analysis/reports/lib/php/NightlyData.php(214): ServerIO->getData(Array, 'counts')
#2 /srv/suma/app/analysis/reports/lib/php/NightlyData.php(477): NightlyData->processData('20160119')
#3 /srv/suma/app/analysis/reports/lib/php/nightly.php(45): NightlyData->getData('20160119')
```

When I try to use the analysis web interface, I get a generic 500 with an empty message.  Nothing gets written to the apache log.

```
Notice!

There was a problem generating the report. Please try again or contact your system administrator.

Error Code: 500

Error Message:
```

Initially, I thought maybe it was a permissions error, so I disabled SELinux and chowned everything 777, but to no avail. I'm on CentOS 7.  The rest of the application does seem to be functioning.

**Comment by bretdavidson** [comment]
Hi Jason,

Try setting the "showErrors" property in the analysis config to true and
see if a more helpful error message appears. If that doesn't help, could
you send me your config file? You may e-mail me at bddavids@ncsu.edu if you
prefer.

Thanks,

Bret

**Comment by jsnshrmn** [comment]
Bret,

Thanks for the prompt reply!  Yes, setting the configuration to display errors seems like a good place to start. /headdesk.

Here is what I'm getting now:
```

Notice!

There was a problem generating the report. Please try again or contact your system administrator.

Error Code: 0

Error Message: Data.getData Timeout
```

**Comment by jsnshrmn** [comment]
Another bit of potentially useful information:
We run our boxes behind a reverse proxy and are using ssl everywhere.  My initial config specified the publicly routable URL for this service.  As a troubleshooting step, I've also tried specifying the private URL for the service using cleartext (curl doesn't know about our backend certs). I still get the same error in this case.

**Comment by bretdavidson** [comment]
Hi Jason,

Could you e-mail me your config files? (bddavids@ncsu.edu)

Thanks,

Bret

**Comment by jsnshrmn** [comment]
Config sent

**Comment by jsnshrmn** [comment]
Okay, there were a couple of issues here:
1) there are unlisted php module dependencies
mbstring and dom
are not default php extensions.  I bet they come by default in your distro.
In centos7 I installed the following two packages to get these extensions:
php-mbstring
php-xml (contains dom)

2) logging is definitely not working as expected on CentOS.  After fiddling with php.ini, turning on showErrors will print errors both in the interface and in the apache error log. This was the only way I could get Suma to write to a logfile. The printed errors break the json response for reporting, so I had to turn it back off.

I do have reporting working now, though.

**Comment by jsnshrmn** [comment]
See PR#39 for a proposed update to the installation docs. 

I'll try to spend a little time looking at how Suma is trying to write errors and why that's not working for me.

**Comment by bretdavidson** [comment]
Ah, interesting. Nice catch on the dependencies, I've merged your pull
request.

Let me know what you find out with the logging.

Best,

Bret

**Comment by jsnshrmn** [comment]
Okay, I discovered the root of my logging woes.  See PR#40.

**Comment by bretdavidson** [comment]
Great! Closing this thread in the meantime.
