### ISSUE TITLE
Enter Totals (instead of tapping) (Enhancement Request)

### ISSUE THREAD

**Issue by lpmagnuson** [cazzerson/Suma#46]
Hello,

The library consortium I work for has several institutions testing out Suma, and our testers are finding that having to tap for each count is very time consuming.  We'd like to request an enhancement that would enable a user in the client to either:

a) Select a number (e.g., 5, 10, 15) in addition to single taps OR
b) Type in a number (e.g., 23) in addition to single taps

This would save a huge amount of time when gathering data.  

Thanks so much for developing Suma!  It is totally awesome.  If this enhancement isn't possible in the near future, I may have some time over the summer to work on this and will submit a pull request.  Thanks for considering this request!

Lauren

**Comment by bretdavidson** [comment]
Hi Lauren!

Thanks for reaching out about Suma. This is a good idea and something we are hoping to address in an upcoming new version of the Suma data collection client. In the meantime, you can add the query string `?multiCount=true` to the URL of your current Suma data collection client to expose a "hidden" input field for capturing multiple counts at once. This was implement a few months ago and might require an update to the Suma client if it hasn't been updated in a while.

Hope this helps!

Thanks,

Bret

**Comment by cappadona** [comment]
Thanks @bretdavidson! Just a quick heads up to anyone else looking to implement this hidden feature to  ensure that you're running at least [v2.13.1](https://github.com/cazzerson/Suma/releases/tag/v2.13.1).
