### ISSUE TITLE
Keep activities selected when entering counts (Enhancement Request)

### ISSUE THREAD

**Issue by lpmagnuson** [cazzerson/Suma#47]
I'd like to request an enhancement that would enable the user to make activity selection "sticky" when doing counts.

Our users have found that having to reselect activities for each count is time consuming, and have suggested an option like enabling users to select an activity and do multiple counts with that activity selected.  

One idea would be to have the activities work as a kind of "toggle" rather than a button that gets deselected upon doing the count.

This might be something I will have time to work on during the summer; if so I will submit a pull request.

Thanks again for developing SUMA!

**Comment by bretdavidson** [comment]
Hi Lauren,

Thanks for reaching out about Suma. As mentioned in issue #46, we are currently working on a new Suma data collection client and are considering ways of meeting this need as part of this work. We'll be discussing this in the coming months in our Gittr chat room if you want to join!

Thanks,

Bret
