### ISSUE TITLE
Select JavaScript framework

### ISSUE THREAD

**Issue by bretdavidson** [cazzerson/Suma#48]

**Comment by cappadona** [comment]
Hey Bret, as promised, here are the frameworks/libraries we've recently considered for some of our own apps at Mann Library. We haven't fully evaluated all of these, an any that we did were done so under the context of supplementing/extending a Rails app, so not sure how helpful this will be.

* [Angular 2](https://angular.io)
* [Bacon](https://baconjs.github.io)
* [Cycle](http://cycle.js.org)
* [Koa](http://koajs.com)
* [Meteor](https://www.meteor.com)
* [Mithril](http://mithril.js.org)
* [React](http://facebook.github.io/react)
* [Sails](http://sailsjs.org)
* [Vue](http://vuejs.org)

[Express](http://expressjs.com) based:
* [Keystone](http://keystonejs.com)
* [Kraken](http://krakenjs.com)
* [MEAN](http://mean.io)

I hope this doesn't only add to the madness :)

**Comment by bretdavidson** [comment]
Hi Nick,

Thanks a bunch for the links, I'm tossing a few comparison articles here as well.

Bret

http://blog.backand.com/angular-2-vs-react/
https://medium.com/@l1ambda/mithril-vs-angular-vs-react-d0d659c24bae#.l8037wb9n
http://www.ociweb.com/resources/publications/sett/comparison-of-angular-2-and-react/

**Comment by bretdavidson** [comment]
Some more reading: http://www.sitepoint.com/react-alternatives-preact-virtualdom-deku/

**Comment by bretdavidson** [comment]
Angular 2 Release Candidate notes: https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by bretdavidson** [comment]
Going with Angular 2!
