### ISSUE TITLE
Select CSS frameworks

### ISSUE THREAD

**Issue by bretdavidson** [cazzerson/Suma#49]

**Comment by cappadona** [comment]
* [Normalize](https://github.com/JohnAlbin/normalize-scss) for consistent base across browsers
* [Bourbon](http://bourbon.io) for utility mixins
* [Bitters](http://bitters.bourbon.io) for scaffolding
* [Breakpoint](http://breakpoint-sass.com) for media queries
* [Susy](http://susy.oddbird.net) for layout/grid

If we end up using the [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter), we'll want to review AngularClass/angular2-webpack-starter#136 and [the wiki](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-SCSS-in-components) so we can include the above as global styles while also including more specific styles per component.

If we're looking for ready-to-go components, [Angular Material](https://material.angular.io) might be a good option to add to the mix, although still in alpha. Obviously, this calls for more thorough testing but my initial explorations of its responsiveness on touch devices have been promising. More details in [this clip from ng-conf 2016](https://www.youtube.com/watch?v=rRiV_b3WsoY&feature=youtu.be&t=4m20s).
