### ISSUE TITLE
Select build system

### ISSUE THREAD

**Issue by bretdavidson** [cazzerson/Suma#50]

**Comment by bretdavidson** [comment]
Hi Nick,

Here are a few JS build system comparisons/puff pieces I've been trying to make sense of. One thing I'm struggling with is understanding the level at which these various libraries operate. Some seem to be more geared to module loading and management and others seem to be focused on traditional front end tasks like concatenation, minifying, etc. 

Thanks,

Bret

JSP v Webpack
http://ilikekillnerds.com/2015/07/jspm-vs-webpack/

SystemJS (I see this referenced in some angular tutorials, do you know much about it?)
https://github.com/systemjs/systemjs

WebPack compared
http://survivejs.com/webpack_react/webpack_compared/

**Comment by cappadona** [comment]
We've discussed this and we're leaning towards following the current trend in the [Angular 2 community](https://angular.io/docs/ts/latest/guide/webpack.html), gravitating to webpack via [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter). There's a [`material2` branch](https://github.com/AngularClass/angular2-webpack-starter/tree/material2) if we end up wanting to use Material Design components. More details in #49.

There's also an [experimental version](https://github.com/gdi2290/angular2-webpack2-starter) of the starter kit targeting webpack 2, which provides us with some options if the stars align with our roadmap and a stable second major release of webpack.
