### ISSUE TITLE
Select browser database library

### ISSUE THREAD

**Issue by bretdavidson** [cazzerson/Suma#51]

**Comment by cappadona** [comment]
Stumbled upon [fortune.js](http://fortunejs.com) a while back and thought it might be useful here.

**Comment by cazzerson** [comment]
Thanks, Nick! Looks like it's missing the Web SQL and/or localStorage
adapters that may be necessary for broad browser support:

http://fortunejs.com/plugins/
http://caniuse.com/indexeddb

Another useful resource:

https://nolanlawson.com/2015/09/29/indexeddb-websql-localstorage-what-blocks-the-dom/

Especially:

http://mozilla.github.io/localForage/
https://google.github.io/lovefield/

Jason

**Comment by cazzerson** [comment]
Although we'll need to do some work to map the current schema and data management processes to a key-value store, [localForage](https://github.com/mozilla/localForage) looks like the best option for us. It supports multiple underlying storage systems, has a large and active user community, and is simple to use.
