### ISSUE TITLE
Set Timezone?

### ISSUE THREAD

**Issue by lpmagnuson** [cazzerson/Suma#62]
Is there a way to change the timezone for the web analytics reports?  

Our cloud server lives in Pacific time, but our libraries are on Eastern time.  

I know there's a way to change the timezone in the nightly reports, but I'm wondering about the Analytics Reports interface.  

Apologies if I've overlooked something totally obvious about how to set this.

Thanks!

Lauren

**Comment by jengalas** [comment]
It's been a few months since I set this up, but I recall creating an .htaccess in the app root consisting of the line `php_value date.timezone America/New_York`. There might be a better way that I'm not aware of.

**Comment by lpmagnuson** [comment]
Thanks @jengalas !  Yup that method works, but because I'm running a bunch of instances for a consortium, I decided to set it in php.ini for the server, which also seems to work for data going forward.

**Comment by cazzerson** [comment]
@jengalas @lpmagnuson I just want to say that I love seeing Suma folks helping each other. Thanks for making my day!
