### ISSUE TITLE
Can't get past admin console page

### ISSUE THREAD

**Issue by dguertin** [cazzerson/Suma#64]
When I log in to the Suma Administrative Tools page, I'm presented with links for:

Edit locations
Edit initiatives
Direct JSON Import
Top Menu 
Logout

When I hover over the links, they show the URLs they're supposed to go to (sumaserver/admin/locations. etc.). But when I click on any of them, they just take me back to the admin login page. I've turned on debugging and don't see any additional information, and also don't see anything helpful in the Apache logs.

Any ideas about where to look for the problem?

Thanks,
Dave

**Comment by bretdavidson** [comment]
Hi,

Thanks for reaching out about Suma. Some things to check:

1) Verify that the suma log file exists and is writable by the web server.

2) Verify that the path to the suma log file is correct in `service/config/config.yaml`. 

3) Did you enable the optional session security by creating a session.yaml file in `services/config/session.yaml`? If so, you may want to verify the configuration paths, etc. Also, ensure that your browser is storing cookies.

Best,

Bret

**Comment by bretdavidson** [comment]
Hi Dave,

Any updates on how this is going?

Bret

**Comment by dguertin** [comment]
I've just figured this out. It seems the default PHP installation from the Red Hat repository does not include the PDO extension. I uninstalled PHP, and reinstalled it from the Webtatic repository, which does include the PDO extension. Everything looks to be working correctly now.

If there was something in the installation instructions listing PDO as a requirement, I must have missed it.

Dave
