### ISSUE TITLE
Reporting Error

### ISSUE THREAD

**Issue by DouglasJ99** [cazzerson/Suma#66]
I am attempting to install Suma on a test VM running RHEL7, and have been able to get everything working except the Reports page. I should note that during the database setup, I used the database script schema.sql, not the script with examples. I went to the admin page and successfully created test initiatives, locations, and activities and I can successfully send counts to the server. However when I visit and the “reports” web page, and try to run a report I get `Error Code:  500` with no "Error Message". I did discover that I forgot to install php-mbstring, but now im getting:
`There was a problem generating the report. Please try again or contact your system administrator.
Error Code: 500
Error Message: No initiatives found. Please create an initiative in the Suma admin tools.`

ANY advice on this error and how I can get the report page working would be greatly appreciated!

Thanks!

**Comment by cazzerson** [comment]
Solved by installing php-xml package.
